name = "Simplev1"
uid = "1b6a5b60-3jfe-4900-935b-8e24867b56f8"
version = 1
description = "Plays Simple. UEF only!"
author = "Leon F"
url = "N/A"
icon = "/mods/Titan/titanmodicon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
